Repository mpi2/impc-api, pull requests merged in 2024-10, with the labels that each got.

#15 Rename module and reorder libraries
  impc_api_helper/MANIFEST.in
  impc_api_helper/impc_api_helper/temp.py
  impc_api_helper/pytest.ini
  impc_module/CONTRIBUTING.md
  impc_module/LICENSE
  impc_module/MANIFEST.in
  impc_module/README.md
  impc_module/impc_api/__init__.py
  impc_module/impc_api/batch_solr_request.py
  impc_module/impc_api/solr_request.py
  impc_module/impc_api/utils/__init__.py
  impc_module/impc_api/utils/core_fields.json
  impc_module/impc_api/utils/validators.py
  impc_module/impc_api/utils/warnings.py
  impc_module/pyproject.toml
  impc_module/pytest.ini
  impc_module/setup.py
  impc_module/tests/__init__.py
  impc_module/tests/test_batch_solr_request.py
  impc_module/tests/test_helpers.py
  impc_module/tests/test_solr_request.py
Labels: documentation, refactor

#17 Set up publishing `impc_api` package from GitHub
  .github/workflows/publish.yml
  impc_module/pyproject.toml
  impc_module/setup.py
Labels: enhancement

#20 Remove `setup.py` and always build with `pyproject.toml`
  .github/workflows/publish.yml
  pyproject.toml
  setup.py
Labels: refactor

#23 [Solr_request] - Unexpected behaviour of validate flag for comma and space separated fields
  impc_api/utils/core_fields.json
  impc_api/utils/validators.py
  tests/test_solr_request.py
Labels: bug
